# Generated by Django 4.2 on 2024-10-14 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cathegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent_cathegory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='KaptyorkaApp.cathegory')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('img_path', models.CharField(max_length=350)),
                ('description', models.CharField(max_length=2000)),
                ('amount', models.IntegerField()),
                ('cathegory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='KaptyorkaApp.cathegory')),
            ],
        ),
        migrations.CreateModel(
            name='RentAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=400)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('fact_start_date', models.DateTimeField(blank=True, null=True)),
                ('fact_end_date', models.DateTimeField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueEquipment',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='KaptyorkaApp.equipment')),
                ('deterioration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OldPriceOfEquipment',
            fields=[
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='KaptyorkaApp.equipment')),
                ('datetime', models.DateTimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'unique_together': {('equipment', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='RentedEquipment',
            fields=[
                ('accounting', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='KaptyorkaApp.rentaccounting')),
                ('deterioration', models.IntegerField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='KaptyorkaApp.equipment')),
            ],
            options={
                'unique_together': {('accounting', 'equipment')},
            },
        ),
        migrations.CreateModel(
            name='RentedCountableEquipment',
            fields=[
                ('accounting', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='KaptyorkaApp.rentaccounting')),
                ('amount', models.IntegerField()),
                ('returned_amount', models.IntegerField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='KaptyorkaApp.equipment')),
            ],
            options={
                'unique_together': {('accounting', 'equipment')},
            },
        ),
    ]
