# Generated by Django 4.2 on 2025-05-26 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KaptyorkaApp', '0004_rentclient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentClient',
            new_name='Client',
        ),
        migrations.RemoveField(
            model_name='rentaccounting',
            name='username',
        ),
        migrations.AddField(
            model_name='rentaccounting',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='KaptyorkaApp.client'),
        ),
    ]
