# Generated by Django 4.2 on 2025-05-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KaptyorkaApp', '0005_rename_rentclient_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentaccounting',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentaccounting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
