# Generated by Django 4.2 on 2025-05-27 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KaptyorkaApp', '0006_rentaccounting_is_free_rentaccounting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldpriceofequipment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentedcountableequipment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oldpriceofequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='KaptyorkaApp.equipment'),
        ),
        migrations.AlterField(
            model_name='rentedcountableequipment',
            name='accounting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='KaptyorkaApp.rentaccounting'),
        ),
        migrations.AlterField(
            model_name='rentedcountableequipment',
            name='returned_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rentedequipment',
            name='accounting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='KaptyorkaApp.rentaccounting'),
        ),
        migrations.AlterField(
            model_name='uniqueequipment',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='KaptyorkaApp.equipment'),
        ),
    ]
