# Generated by Django 4.2 on 2025-05-27 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KaptyorkaApp', '0007_oldpriceofequipment_id_rentedcountableequipment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldpriceofequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KaptyorkaApp.equipment'),
        ),
        migrations.AlterField(
            model_name='rentedcountableequipment',
            name='accounting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KaptyorkaApp.rentaccounting'),
        ),
        migrations.AlterField(
            model_name='rentedcountableequipment',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='KaptyorkaApp.equipment'),
        ),
    ]
