# Generated by Django 4.2 on 2023-08-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RomantikApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspost',
            old_name='cathegory',
            new_name='user',
        ),
    ]
