# Generated by Django 4.2 on 2023-11-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RomantikApp', '0006_userinfo_email_userinfo_phone_userinfo_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_email_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_phone_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_telegram_public',
            field=models.BooleanField(default=False),
        ),
    ]
