# Generated by Django 4.2 on 2023-11-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RomantikApp', '0007_userinfo_is_email_public_userinfo_is_phone_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
