# Generated by Django 4.2 on 2024-03-14 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RomantikApp', '0008_alter_userinfo_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.AddField(
            model_name='newspost',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='was_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RomantikApp.newspost')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RomantikApp.tag')),
            ],
        ),
    ]
