# Generated by Django 4.2 on 2024-03-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RomantikApp', '0009_tag_newspost_last_update_newspost_was_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChannelParserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('last_post_id', models.IntegerField()),
            ],
        ),
    ]
