# Generated by Django 4.2 on 2024-03-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RomantikApp', '0011_telegramchannelparserdata_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchannelparserdata',
            name='channel',
            field=models.CharField(default='my_awesome_channel', max_length=45),
        ),
    ]
