# Generated by Django 4.2 on 2024-03-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RomantikApp', '0012_alter_telegramchannelparserdata_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchannelparserdata',
            name='last_update',
            field=models.DateTimeField(auto_created=True, default='2023-06-06 00:00:00'),
        ),
    ]
