# Generated by Django 4.2 on 2024-03-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RomantikApp', '0014_telegrampostid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramChannelParserData',
        ),
        migrations.AlterField(
            model_name='newspost',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default='2023-06-06 00:00:00'),
        ),
    ]
