# Generated by Django 4.2 on 2024-03-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RomantikApp', '0015_delete_telegramchannelparserdata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramPostId',
        ),
    ]
