# Generated by Django 4.2 on 2024-03-17 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RomantikApp', '0016_delete_telegrampostid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramPostId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='my_awesome_channel', max_length=45)),
                ('post_tg_id', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RomantikApp.newspost')),
            ],
        ),
    ]
